server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.106:8848
    sentinel:
      transport:
        dashboard: 192.168.0.106:8080
        port: 192.168.0.106:8719
  zipkin:
    base-url: http://192.168.0.106:9411
    sender:
      type: web
    discovery-client-enabled: true
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.65.190
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.65.190:3306/guli_cart?useSSL=false
    username: root
    password: 123456Abc@
feign:
  sentinel:
    enabled: true
#jwt配置
jwt:
  pubKeyPath: D:\IdeaProjects\project-rookie\rsa\rsa.pub
  cookieName: GMALL-TOKEN
  userKey: userKey
  expire: 8640000
# 数据库自增
mybatis-plus:
  global-config:
    db-config:
      id-type: auto