server:
  port: 18083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.106:8848
    sentinel:
      transport:
        dashboard: 192.168.0.106:8080
        port: 8719
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://192.168.0.106:9411
    discovery-client-enabled: false
    sender:
      type: web
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.65.190:3306/guli_wms?useSSL=false
    username: root
    password: 123456Abc@
  redis:
    host: 192.168.65.190
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/wms/**/*.xml
  type-aliases-package: com.atguigu.gmall.wms.entity
  global-config:
    db-config:
      id-type: auto

